// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Channel struct {
	ChannelID  string
	ChannelUrl string
	Name       string
}

type Feed struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	UserID    int32
}

type FeedsChannel struct {
	FeedID    int32
	ChannelID string
}

type User struct {
	ID        int32
	GoogleID  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
