// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

type Channel struct {
	ChannelID       string
	ChannelUploadID string
	ChannelHandle   string
	ChannelUrl      string
}

type Feed struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	UserID    string
}

type FeedsChannel struct {
	FeedID    int32
	ChannelID string
}

type User struct {
	FbUserID  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
