// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
	"time"
)

const containsUserByGoogleId = `-- name: ContainsUserByGoogleId :one
SELECT EXISTS (
    SELECT 1 FROM users
    WHERE google_id = $1
)
`

func (q *Queries) ContainsUserByGoogleId(ctx context.Context, googleID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, containsUserByGoogleId, googleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const containsUserById = `-- name: ContainsUserById :one
SELECT EXISTS (
    SELECT 1 FROM users
    WHERE id = $1
)
`

func (q *Queries) ContainsUserById(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, containsUserById, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (google_id, created_at, updated_at)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id
`

type CreateUserParams struct {
	GoogleID  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.GoogleID, arg.CreatedAt, arg.UpdatedAt)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteUserById = `-- name: DeleteUserById :one
DELETE FROM users WHERE id = $1
RETURNING id, google_id, created_at, updated_at
`

func (q *Queries) DeleteUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, deleteUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, google_id, created_at, updated_at FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GoogleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserById = `-- name: GetUserById :one
SELECT id, google_id, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserIdByGoogleId = `-- name: GetUserIdByGoogleId :one
SELECT id FROM users
WHERE google_id = $1
`

func (q *Queries) GetUserIdByGoogleId(ctx context.Context, googleID string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserIdByGoogleId, googleID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
