// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
	"time"
)

const containsUserByFirebaseId = `-- name: ContainsUserByFirebaseId :one
SELECT EXISTS (
    SELECT 1 FROM users
    WHERE fb_user_id = $1
)
`

func (q *Queries) ContainsUserByFirebaseId(ctx context.Context, fbUserID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, containsUserByFirebaseId, fbUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (fb_user_id, created_at, updated_at)
VALUES (
    $1,
    $2,
    $3
)
`

type CreateUserParams struct {
	FbUserID  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.FbUserID, arg.CreatedAt, arg.UpdatedAt)
	return err
}

const deleteUserById = `-- name: DeleteUserById :exec
DELETE FROM users WHERE fb_user_id = $1
`

func (q *Queries) DeleteUserById(ctx context.Context, fbUserID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserById, fbUserID)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT fb_user_id, created_at, updated_at FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.FbUserID, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserById = `-- name: GetUserById :one
SELECT fb_user_id, created_at, updated_at FROM users
WHERE fb_user_id = $1
`

func (q *Queries) GetUserById(ctx context.Context, fbUserID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, fbUserID)
	var i User
	err := row.Scan(&i.FbUserID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
